#!/usr/bin/python3

import turtle
turtle.shape ("turtle")
turtle.speed(100)
for m in range (12):
    for i in range (360):
        turtle.right(1)
        turtle.forward(1+m/10)

    for i in range (360):
        turtle.left(1)
        turtle.forward(1+m/10)

