#!/usr/bin/python3

import turtle
turtle.shape ("turtle")
n=360/12
for i in range(12):
    turtle.right(180+n)
    turtle.forward(100)
    turtle.stamp()
    turtle.penup()
    turtle.right(180)
    turtle.forward (100)
    turtle.pendown()


